### ISSUE TITLE
Get Stage1 playable

### ISSUE THREAD

**Issue by vulpineblaze** [vulpineblaze/framework_demoes#17]
Right now the player doesn't have much to do in Stage1. I don't wanna go crazy with non-combat stuff here, but mocking up a few things could be nice. Really, just having interesting enough shit to shoot at would be sufficient. 

Objective:
- Complete other combat related issues that involve Stage1 content
- Add more things to kill in Stage1
  - possibly have a spawner object?
    - When mining, checks if stage has no ST
    - if no other ST, spawn ST
- mockup other content, but doesnt have to be functional
  - like have the planet-mining increase the resources in the HUD or something
  - nothing fancy required, just a lil spit & polish

**Comment by jsmunster** [comment]
Take 20 minutes try to make bad guy spawner, if not just drag and drop a couple of bad guys and call it DONE.

**Comment by jsmunster** [comment]
@vulpineblaze implemented this in one of the globalObjects.
