### ISSUE TITLE
Enemies always being active upon start

### ISSUE THREAD

**Issue by jsmunster** [vulpineblaze/framework_demoes#20]
- Figure out how to make bad guys be inactive till an appropriate distance from player and/or stimuli

**Comment by vulpineblaze** [comment]
did this under iss5 branch:
- Set ST's rigidbody to 'start asleep'
- fixed movetoplayerscript, since it was waking up ST by applying movement
- fixed STscript since it was firing wedges weapons, even while asleep. 

These changes will be pushed to master with iss5's push.
