### ISSUE TITLE
Camera is stationary on player

### ISSUE THREAD

**Issue by jsmunster** [vulpineblaze/framework_demoes#21]
- Make camera move slightly in front of player; A.K.A a slight shift forward in the direction of travel.

**Comment by vulpineblaze** [comment]
This was surprisingly difficult. 

Its working, but its makes the player prefab ugly.

The object that is moved by WASD drags the object with the sprites and turrets behind it. 

Everything is named wrong now, and maybe even need to refactor PlayerScript. 

I'm dumb and pushed straight to master.
