### ISSUE TITLE
Numerical Health display not updating.

### ISSUE THREAD

**Issue by jsmunster** [vulpineblaze/framework_demoes#29]
Numerical health display in the hud at the upper left corner is not updating correctly, but the health BAR is. Maybe. Sort of.

**Comment by vulpineblaze** [comment]
@jsmunster  found an unrelated bug:

if Unity fails to find a component in child in and Update loop (eg I deleted SecondaryWeaponScript from blue_turret but not from PlayerScript)  if simply fails the script - no code below that point is run.

**Comment by vulpineblaze** [comment]
numerical health display and health bar show correct values. 

Some of the errors found:
- size was 60, increased to 120 to show all text
- health was int, but needed float for laser damage; zero would null the division
