### ISSUE TITLE
ST lasers collide with planet

### ISSUE THREAD

**Issue by vulpineblaze** [vulpineblaze/framework_demoes#41]
Currently the ST laser collide with the planet

The ST laser should not collide with anything except the player

**Comment by jsmunster** [comment]
Thoughts on probably has something to do with planets collision detection.

**Comment by vulpineblaze** [comment]
add "if not player, do nothing" to raycast

**Comment by jsmunster** [comment]
Raycast returns object hit; getcomponent.healthscript != null

**Comment by vulpineblaze** [comment]
fixed
