### ISSUE TITLE
make saurothrop ship

### ISSUE THREAD

**Issue by vulpineblaze** [vulpineblaze/framework_demoes#5]
- chaser is a good prototype
- replace sprite
- make sure laser lines up
- make sure fusion bombs lines up, eventually

**Comment by vulpineblaze** [comment]
maybe this is long-term, and outside the scope of this issue...

I'd like to have nested sprites like so:
- empty, just move & rotate scripts
  - five segments ~72 degrees aparts

the top layer controls where the ship is going and pointing
the five segments get:
- sprites
- health & damage
- AI to determine when to shoot:
  - laser
  - fusion bombs

and when one dies, it "explodes" switching to a "Destroyed" sprite. both types have a random pool so each ship looks different. each time a piece is destroyed, there's an increasing chance that the whole ship is destroyed. If not triggered by the last piece, then the enemy just exists, like a asteroid, after destruction, and the player can mine it.

but like i said, there a lot of mechanic we dont need _now_ so it might be out of scope..

**Comment by vulpineblaze** [comment]
Currently implemented:
- the overall container + move sprites, with some clunky rotation
- The 5 wedges with static sprites
- health and damage
  - PartialHealthScript handles wedge damage, and then on 0 hp, passes 'real' damage to top level gameObject. Does not destroy wedge.
  - currently mis-passes hp to top level, 50 hp became 38 after 5 wedges @ 1hp/wedge. (7 extra damage was applied by unkown cause). My current guess is that the Damage() call takes too long, and so it applied more than once during combat. 
- Saurothrop script only fires with the closest wedge, the other 4 remain dormant. 
- ST script does not take into account destroyed wedges
- destroyed sprite anim not implemented
- 'wreckage' state for top level gameObject not implemented either.

**Comment by vulpineblaze** [comment]
@jsmunster Close this issue and make the remaining items into non-milestone issues?

**Comment by jsmunster** [comment]
@vulpineblaze has completed this issue.
