### ISSUE TITLE
start button doesnt work at 1024x768 resolution

### ISSUE THREAD

**Issue by vulpineblaze** [vulpineblaze/framework_demoes#55]
as per
https://www.facebook.com/groups/301520512729/10153273934092730/?comment_id=10153273950822730&notif_t=group_comment

**Comment by jsmunster** [comment]
Probably also a problem with other 4:3 aspect ratio resolutions.

**Comment by vulpineblaze** [comment]
this is probably the first and biggest issue, we may have lost a few players over this bug.

**Comment by tammello** [comment]
If you go into windowed it should work on any resolution. Worked for me,
and I tested it in all of them.

**Comment by vulpineblaze** [comment]
Still not fixed, is a Unity bug, not ours. 

Gonna need to switch to game objects as buttons

http://answers.unity3d.com/questions/1170085/only-detect-button-click-event.html

**Comment by vulpineblaze** [comment]
I made a gameobject: (StartButton)  
- with the sprite "Button1"  
- child with text mesh
  - set font to 20,  then scaled the text mesh to .3 to make sharpness
- added script with OnMouseDown() method, put loadlevel() in there

relevant link : http://coffeebreakcodes.com/mouse-click-on-game-object-unity3d-c/

This is the accepted workaround for this issue. All GUI components are going to need to be switched over.

**Comment by vulpineblaze** [comment]
solved via workaround
