### ISSUE TITLE
make fusion bombs *derp*

### ISSUE THREAD

**Issue by vulpineblaze** [vulpineblaze/framework_demoes#7]
- bomb bullet
  - fly forward, dumb fire
- make explosion animation
  - and the corresponding sprites
- have that expanding animation do collision
- and deal damage

**Comment by jsmunster** [comment]
oncollide = playanimation; You have bomb, it collides, it dies, plays one animation, spawns "explosion sprite" which expands and collapses that holds the collision box which will deliver damage to objects.

**Comment by jsmunster** [comment]
Secondary weapon functionality has been implemented. This issue should have been a minimum of 2 issues from the get go. Closing and reopening for further dev.
