### ISSUE TITLE
investigate upgrades

### ISSUE THREAD

**Issue by vulpineblaze** [vulpineblaze/framework_demoes#8]
- player has stats that affect gameplay
- player can change turrets, bullets
  - engine animation too?
- have some sort of resource?

**Comment by vulpineblaze** [comment]
@jsmunster the GlobalObjects handle this, we have a global player and HUD object that have this data, and so from here we should close this issue and each stat should be broken into individual issues. We should meet up and itemize a bunch of these.

**Comment by jsmunster** [comment]
Investigation completed. Ongoing implementation.
