### ISSUE TITLE
investigate HUD

### ISSUE THREAD

**Issue by vulpineblaze** [vulpineblaze/framework_demoes#9]
- need to display life
- energy / resources
- direction/distance to other things on the map?
- menu bars
  - save
  - settings
  - inventory
  - upgrades
  - ?galaxy map?

**Comment by vulpineblaze** [comment]
Text is on the screen showing health, resources, and kills. Health and resources update correctly.
Kills is in healthscript, supposed to catch when something dies and increment. Currently only counts player deaths.

**Comment by vulpineblaze** [comment]
@jsmunster We need to sit down with this one and expand into smaller issues - the HUD exists so this should be closed.

**Comment by jsmunster** [comment]
Investigation Complete. Will spawn more issues.
